export enum Constants {
  DATABASE_CONNECTION = 'DATABASE_CONNECTION',
  
	FORUM_REPO = 'FORUM_REPOSITORY',
	REPLY_REPO = 'REPLY_REPOSITORY',
	THREAD_REPO = 'THREAD_REPOSITORY',
	USER_REPO = 'USERS_REPOSITORY'
}

export const PAGE_SIZE = 10
